/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BTableSimple: typeof import('bootstrap-vue-next')['BTableSimple']
    BTbody: typeof import('bootstrap-vue-next')['BTbody']
    BTd: typeof import('bootstrap-vue-next')['BTd']
    BTh: typeof import('bootstrap-vue-next')['BTh']
    BTr: typeof import('bootstrap-vue-next')['BTr']
    CityMap: typeof import('./src/components/CityMap.vue')['default']
    FlatInfo: typeof import('./src/components/FlatInfo.vue')['default']
    FooterInfo: typeof import('./src/components/FooterInfo.vue')['default']
    IconWithText: typeof import('./src/components/IconWithText.vue')['default']
    InfoTable: typeof import('./src/components/InfoTable.vue')['default']
    PhotoGallery: typeof import('./src/components/PhotoGallery.vue')['default']
  }
}
